### ISSUE TITLE
Broken link in the file enable-autocomplete.md

### ISSUE THREAD

**Issue by giesan** [score-spec/docs#75]
Hello everyone,

while reading the documentation I noticed that in the file `content/en/docs/reference/score-cli/enable-autocomplete.md` the link <https://github.com/spf13/cobra/blob/main/shell_completions.md> refers to a non-existent page.

I think this refers to the page <https://github.com/spf13/cobra/blob/main/site/content/completions/_index.md>.

Best regards
andy

**Comment by sujaya-sys** [comment]
@giesan thanks for posting this issue! With the new documentation update we decided to remove the `/enable-autocomplete` page for now. It can be found within the CLI reference now, see here for score-compose for example: https://docs.score.dev/docs/score-implementation/score-compose/#completion - If this looks all good to you now feel free to close the issue 🙂 Thank you!

**Comment by giesan** [comment]
It looks good to me now.
