### ISSUE TITLE
The title in the table of contents does not match the title in the text

### ISSUE THREAD

**Issue by giesan** [score-spec/docs#76]
Hello everyone,

in the file `content/en/docs/environment variables/environment-variables-compose.md`, the title `Environment configuration in file` in the table of contents does not correspond to the title in the text `Environment configuration file`.

For this reason, the link in the table of contents does not work either.

Best regards
andy

**Comment by sujaya-sys** [comment]
@giesan thanks for reporting this! We released a new version of the Score docs which should have resolved this issue. The page on environment variables now live here and has been slightly reworked: https://docs.score.dev/docs/how-to/environment-variables - If this looks all good to you feel free to close this issue. Thank you!

**Comment by giesan** [comment]
It looks good to me now.
